<?php
/**
 * ProjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Localizer\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Localizer API
 *
 * PHP SDK for https://localizer.io
 *
 * OpenAPI spec version: 1.0
 * Contact: support@localizer.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Localizer\Client;

/**
 * ProjectTest Class Doc Comment
 *
 * @category    Class */
// * @description Project
/**
 * @package     Localizer\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Project"
     */
    public function testProject()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {

    }

    /**
     * Test attribute "counter_sections"
     */
    public function testPropertyCounterSections()
    {

    }

    /**
     * Test attribute "last_activity"
     */
    public function testPropertyLastActivity()
    {

    }

}
