<?php
/**
 * LanguagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Localizer\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Localizer API
 *
 * PHP SDK for https://localizer.io
 *
 * OpenAPI spec version: 1.0
 * Contact: support@localizer.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Localizer\Client;

use \Localizer\Client\Configuration;
use \Localizer\Client\ApiException;
use \Localizer\Client\ObjectSerializer;

/**
 * LanguagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Localizer\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LanguagesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for getLanguages
     *
     * Languages list.
     *
     */
    public function testGetLanguages()
    {

    }

}
