<?php
/**
 * ProjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Localizer\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Localizer API
 *
 * PHP SDK for https://localizer.io
 *
 * OpenAPI spec version: 1.0
 * Contact: support@localizer.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Localizer\Client;

use \Localizer\Client\Configuration;
use \Localizer\Client\ApiException;
use \Localizer\Client\ObjectSerializer;

/**
 * ProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Localizer\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createProject
     *
     * Create project.
     *
     */
    public function testCreateProject()
    {

    }

    /**
     * Test case for createSection
     *
     * Create section.
     *
     */
    public function testCreateSection()
    {

    }

    /**
     * Test case for deleteProject
     *
     * Delete project.
     *
     */
    public function testDeleteProject()
    {

    }

    /**
     * Test case for deleteSection
     *
     * Delete section.
     *
     */
    public function testDeleteSection()
    {

    }

    /**
     * Test case for getProject
     *
     * Project info.
     *
     */
    public function testGetProject()
    {

    }

    /**
     * Test case for getProjects
     *
     * Projects List.
     *
     */
    public function testGetProjects()
    {

    }

    /**
     * Test case for getSection
     *
     * Section info.
     *
     */
    public function testGetSection()
    {

    }

    /**
     * Test case for getSectionTranslations
     *
     * Translations for section on all languages.
     *
     */
    public function testGetSectionTranslations()
    {

    }

    /**
     * Test case for getSections
     *
     * Sections list.
     *
     */
    public function testGetSections()
    {

    }

    /**
     * Test case for updateProject
     *
     * Update project.
     *
     */
    public function testUpdateProject()
    {

    }

    /**
     * Test case for updateSection
     *
     * Update section.
     *
     */
    public function testUpdateSection()
    {

    }

    /**
     * Test case for uploadSectionTranslations
     *
     * Upload translations to section.
     *
     */
    public function testUploadSectionTranslations()
    {

    }

}
